# Generated by Django 3.2.17 on 2023-02-11 00:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('title', models.CharField(default='None', max_length=200, verbose_name='title')),
                ('department', models.CharField(default='None', max_length=200, verbose_name='department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Υπό Επεξεργασία', 'Υπό Επεξεργασία'), ('Οριστικοποιημένη', 'Οριστικοποιημένη'), ('Αποδεκτή', 'Αποδεκτή'), ('Απορρίφθηκε', 'Απορρίφθηκε')], default='Υπό Επεξεργασία', max_length=50, verbose_name='Κατάσταση Αίτησης')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('year', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=personal.models.current_year, null=True, verbose_name='Έτος Αίτησης')),
            ],
            options={
                'verbose_name': 'Αίτηση Χρήστη',
                'verbose_name_plural': 'Αιτήσεις Χρήστών',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Όνομα')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Τμήμα',
                'verbose_name_plural': 'Τμήματα',
            },
        ),
        migrations.CreateModel(
            name='PostgraduatePrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Όνομα')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Τέλους')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.departments', verbose_name='Τμήμα')),
            ],
            options={
                'verbose_name': 'Πρόγραμμα',
                'verbose_name_plural': 'Προγράμματα',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personal.user')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_images')),
            ],
            options={
                'db_table': 'personal_profile',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recom_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('recom_surname', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('recom_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('recom_phone', models.CharField(max_length=100, verbose_name='Τηλέφωνο')),
                ('recom_organism', models.CharField(blank=True, max_length=100, null=True, verbose_name='Οργανισμός')),
                ('recom_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Θέση')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Συστατική Επιστολή',
                'verbose_name_plural': 'Συστατικές Επιστολές',
            },
        ),
        migrations.CreateModel(
            name='ProgramDirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Όνομα Κατεύθυνσης')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.postgraduateprograms', verbose_name='Πρόγραμμα')),
            ],
            options={
                'verbose_name': 'Κατεύθυνση',
                'verbose_name_plural': 'Κατευθύνσεις',
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Τίτλος Εργασίας')),
                ('employer', models.CharField(max_length=100, verbose_name='Εργοδότης')),
                ('duties_description', models.TextField(verbose_name='Περιγραφή Καθηκόντων')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Τέλους')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Προϋπηρεσία Χρήστη',
                'verbose_name_plural': 'Προϋπηρεσία Χρήστη',
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Γλώσσα')),
                ('level', models.CharField(max_length=100, verbose_name='Επίπεδο')),
                ('score', models.CharField(max_length=20, null=True, verbose_name='Βαθμός')),
                ('degree_name', models.CharField(max_length=100, null=True, verbose_name='Όνομα Πτυχίου')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('date_of_acquisition', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Απόκτησης')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ξένη Γλώσσα',
                'verbose_name_plural': 'Ξένες Γλώσσες',
            },
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Τίτλος Σπουδών')),
                ('university', models.CharField(max_length=100, verbose_name='Φορέας')),
                ('average', models.CharField(blank=True, max_length=15, verbose_name='Μέσος Όρος')),
                ('graduation_year', models.CharField(blank=True, max_length=15, verbose_name='Έτος/Αναμενόμενο έτος Αποφοίτησης')),
                ('thesis_title', models.TextField(blank=True, verbose_name='Τίτλος Πτυχιακής')),
                ('thesis_description', models.TextField(blank=True, verbose_name='Περιγραφή Πτυχιακής')),
                ('pdf_degree', models.FileField(blank=True, null=True, upload_to=personal.models.user_directory_path, verbose_name='PDF πτυχίου')),
                ('pdf_thesis', models.FileField(blank=True, null=True, upload_to=personal.models.user_directory_path, verbose_name='PDF πτυχιακής')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('degree_type', models.CharField(choices=[('Προπτυχιακό', 'Προπτυχιακό'), ('Μεαπτυχιακό', 'Μεαπτυχιακό'), ('Σεμινάριο', 'Σεμινάριο'), ('Διαδικτυακά Μαθήματα', 'Διαδικτυακά Μαθήματα')], default='Προπτυχιακό', max_length=50, verbose_name='Τύπος Πτυχίου')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Πτυχίο Χρήστη',
                'verbose_name_plural': 'Πτυχία Χρήστη',
            },
        ),
        migrations.CreateModel(
            name='BasicUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Όνομα')),
                ('surname', models.CharField(max_length=25, null=True, verbose_name='Επώνυμο')),
                ('fatherName', models.CharField(max_length=25, null=True, verbose_name='Όνομα πατέρα')),
                ('motherName', models.CharField(max_length=25, null=True, verbose_name='Όνομα μητέρας')),
                ('afm', models.CharField(max_length=25, null=True, verbose_name='ΑΦΜ')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('birth_date', models.DateField(verbose_name='Ημερομηνία Γέννησης')),
                ('national_id', models.CharField(max_length=50, null=True, verbose_name='Αριθμός Ταυτότητας')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Διεύθυνση')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Βασική Πληροφορία Χρήστη',
                'verbose_name_plural': 'Βασικές Πληροφορίες Χρηστών',
            },
        ),
        migrations.CreateModel(
            name='AssignedProffessors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Γλώσσα')),
                ('level', models.CharField(max_length=100, verbose_name='Επίπεδο')),
                ('score', models.CharField(max_length=20, null=True, verbose_name='Βαθμός')),
                ('degree_name', models.CharField(max_length=100, null=True, verbose_name='Όνομα Πτυχίου')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('date_of_acquisition', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Απόκτησης')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ξένη Γλώσσα',
                'verbose_name_plural': 'Ξένες Γλώσσες',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.postgraduateprograms', verbose_name='Πρόγραμμα'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.CharField(max_length=300, verbose_name='Πρώτη Επιλογή Κατεύθυνσης')),
                ('second_choice', models.CharField(blank=True, max_length=300, null=True, verbose_name='Δεύτερη Επιλογή Κατεύθυνσης')),
                ('third_choice', models.CharField(blank=True, max_length=300, null=True, verbose_name='Τρίτη Επιλογή Κατεύθυνσης')),
                ('reason_of_selection', models.TextField(verbose_name='Λόγος Επιλογής Μεταπτυχιακού')),
                ('other_applications', models.TextField(verbose_name='Άλλες Αιτήσεις σε Μεταπτυχιακά')),
                ('studies_type', models.CharField(choices=[('Μερικής Φοίτησης', 'Μερικής Φοίτησης'), ('Πλήρους Φοίτησης', 'Πλήρους Φοίτησης')], default='Πλήρους Φοίτησης', max_length=50, verbose_name='Τύπος Φοίτησης')),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.application', verbose_name='Αίτηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Επιπρόσθετες Πληροφορίες',
                'verbose_name_plural': 'Επιπρόσθετες Πληροφορίες',
            },
        ),
        migrations.CreateModel(
            name='ApprovedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Εγκεκριμένη Αίτηση Χρήστη',
                'verbose_name_plural': 'Εγκεκριμένες Αιτήσεις Χρήστών',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personal.application',),
        ),
        migrations.CreateModel(
            name='RejectedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Απορριφθείσα Αίτηση Χρήστη',
                'verbose_name_plural': 'Απορριφθείσες Αιτήσεις Χρήστών',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personal.application',),
        ),
    ]
