# Generated by Django 3.2.17 on 2023-02-11 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='personal.user', verbose_name='Χρήστης'),
            preserve_default=False,
        ),
    ]
