# Generated by Django 3.2.17 on 2023-03-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20230304_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedproffessors',
            options={'verbose_name': 'Υπεύθυνος Καθηγητής', 'verbose_name_plural': 'Υπέυθυνοι Καθηγητές'},
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='application',
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='date_of_acquisition',
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='degree_name',
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='level',
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assignedproffessors',
            name='score',
        ),
        migrations.AddField(
            model_name='assignedproffessors',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.postgraduateprograms', verbose_name='Πρόγραμμα'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Τμήμα'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='Φοιτητής', max_length=100, null=True, verbose_name='Τίτλος'),
        ),
    ]
